### ISSUE TITLE
Missing fonts and message: some font thing failed

### ISSUE THREAD

**Issue by codingepaduli** [flathub/org.gnome.Evince#33]
Pdf file (in attachment) is opened, but fonts are missing.

When I start Evince, I got these lines:
```
flatpak run  --verbose org.gnome.Evince 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/io/.local/share/flatpak
F: Opening user flatpak installation at path /home/io/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/io/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2739479457
F: Allocated instance id 1352683812
F: Add values in dir '/org/gnome/evince/', prefix is '/org/gnome/Evince/'
F: Add defaults in dir /org/gnome/Evince/
F: Add locks in dir /org/gnome/Evince/
F: writing D-Conf values to /home/io/.var/app/org.gnome.Evince/config/glib-2.0/settings/keyfile
F: Disallowing network access
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 32 xdg-dbus-proxy --args=34'
F: Running 'bwrap --args 32 evince
```

When Evince has been started and I choose to open the file (in the recent documents), I got these lines in output:
```
some font thing failed
some font thing failed
some font thing failed
some font thing failed
some font thing failed
some font thing failed
some font thing failed
```

This is the file to test.

[LETTERA_NOTIFICA_TRASFERIMENTO_SECONDARIA_II_GRADO_202021_7.pdf](https://github.com/flathub/org.gnome.Evince/files/4851692/LETTERA_NOTIFICA_TRASFERIMENTO_SECONDARIA_II_GRADO_202021_7.pdf)

When I open it with Chromium, I get this image:

![Istantanea_Chromium](https://user-images.githubusercontent.com/52714870/86216013-e5885280-bb6c-11ea-845b-339faeaaff45.png)

When I open it with Evince, I get this:

![Istantanea_Evince](https://user-images.githubusercontent.com/52714870/86216080-018bf400-bb6d-11ea-9e8e-3b1fb9f7ac1d.png)

**Comment by gpoo** [comment]
The document does not have embedded the font. The font it references is Helvetica, which is non-free, and there does not seem to have an alternative font or poppler is not finding it.

**Comment by codingepaduli** [comment]
When I use Evince, not installed by Flatpak, but by Debian repository with ``apt-get install``, I can see the document. Running 
``evince LETTERA_NOTIFICA_TRASFERIMENTO_SECONDARIA_II_GRADO_202021_7.pdf``
I will see this image:
![LETTERA_etc](https://user-images.githubusercontent.com/52714870/114907377-87321500-9e0a-11eb-81f8-a5ba0a628f2f.png)

So I have some font installed from the Debian repository. How can I check I'm using Helvetica and NOT an alternative free font? Any suggestion?

Can't you add an extra non-free package to install ?

Thanks for your great work

**Comment by nsmlzl** [comment]
I have the same issue! This issue is really frustrating.

**Comment by codingepaduli** [comment]
There are a lot of bugs about fonts in flatpak.

Searching in the original repository https://github.com/flatpak/flatpak/ , in the issue page with the filter "is:issue is:open font", it will show a lot of bugs, as you can see here: https://github.com/flatpak/flatpak/issues?page=1&q=is%3Aissue+is%3Aopen+font

**Comment by hadess** [comment]
I can't reproduce the problem here.

Outside the sandbox:

![Screenshot from 2021-08-07 20-20-46](https://user-images.githubusercontent.com/769861/128610420-4df09173-b2df-4029-9c3f-5f8decb28417.png)

Inside the sandbox

![Screenshot from 2021-08-07 20-21-50](https://user-images.githubusercontent.com/769861/128610423-0f2b4721-b6b8-4ef4-b1fe-ecdb433d787b.png)

In both cases it's an Helvetica replacement font that's getting chosen, and it's exported by the host (though it's a user font in the latter case). What does the font properties dialogue look like on your systems when opening a broken file?

You can check whether the font that gets selected is available inside the sandbox with:
```
flatpak run --command="fc-list" org.gnome.Evince | grep -i arial
```
for example

**Comment by thalesmaoa** [comment]
I can't figure how to fix it. But it seems to point to a font that doesn't exist.

```
$ flatpak run --command=sh org.gnome.Evince

[📦 org.gnom[📦 org.gnome.Evince ~]$ ls -lha /run/host/fonts/X11/Type1/qhvr.pfb 
lrwxrwxrwx 1 nfsnobody nfsnobody 51 fev 28  2019 /run/host/fonts/X11/Type1/qhvr.pfb -> ../../../texmf/fonts/type1/public/tex-gyre/qhvr.pfb

[📦 org.gnome.Evince ~]$ ls -lha /run/host/fonts/X11/Type1/../../../texmf/fonts/type1/public/tex-gyre/
ls: não foi possível acessar '/run/host/fonts/X11/Type1/../../../texmf/fonts/type1/public/tex-gyre/': Arquivo ou diretório inexistente
```

**Comment by christianrauch** [comment]
I am facing the same issue with the document [passport-application-form-data.pdf](https://uk.diplo.de/blob/504702/44d9d7561362e438c37e9e7fc5f617f5/passport-application-form-data.pdf). This document has form fields that will not show the content after entering text. I am using flatpak 1.12.4 on Ubuntu 20.04. Another example of a PDF that is affected by this issue is given in the Ubuntu bug tracker at https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1448778. The file [theory_scalar.pdf](https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1448778/+attachment/4385010/+files/theory_scalar.pdf) will not show correctly due to missing fonts.

I originally reported the issue to Evince https://gitlab.gnome.org/GNOME/evince/-/issues/1739 where others could not reproduce this issue using this flatpak. And I also don't have these issues with flatpak 1.12.4 on a Arch Linux VM.

Running `flatpak run --command="fc-list" org.gnome.Evince | grep -i arial` will not return anything on either settings (Ubuntu, Arch).

**Comment by gpoo** [comment]
Try:

```
flatpak run --command=fc-cache org.gnome.Evince -f -v
```

and then open the document again.

**Comment by thalesmaoa** [comment]
I confirm that it does solve the problem.

**Comment by gpoo** [comment]
This is a known issue in flatpak: https://github.com/flatpak/flatpak/issues/3191

**Comment by christianrauch** [comment]
I can also confirm that running `fc-cache` inside the flatpak fixes the issues that I saw with my form and the example PDF with the graph.

However, you have to run this every time the flatpak is installed in a new setup or after cleaning left-over files as the font cache will not persists.

before:
```$ tree $HOME/.var/app/org.gnome.Evince/
├── cache
│   ├── fontconfig
│   └── tmp
├── config
│   ├── glib-2.0
│   │   └── settings
│   ├── ibus
│   │   └── bus
│   └── user-dirs.dirs
└── data
    └── recently-used.xbel

9 directories, 2 files
```

after `flatpak run --command=fc-cache org.gnome.Evince -f -v`:
```
$ tree $HOME/.var/app/org.gnome.Evince/
├── cache
│   ├── fontconfig
│   │   ├── 02c3d2a553cc0a59ef9c1e729da08704-le64.cache-7
│   │   ├── 0ddbdbd750e3249d438f72b69cb90ce5-le64.cache-7
│   │   ├── [...]-le64.cache-7
│   │   ├── CACHEDIR.TAG
│   │   └── [...]-le64.cache-7
│   └── tmp
├── config
│   ├── glib-2.0
│   │   └── settings
│   ├── ibus
│   │   └── bus
│   └── user-dirs.dirs
└── data
    └── recently-used.xbel

9 directories, 104 files
```
